name: Build zynthbox-plugin-synthv1-lv2 deb

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    container:
      image: debian:bookworm
      env:
        DEBIAN_FRONTEND: noninteractive
        APTLY_REPO: testing
        RELEASE: bookworm
        BUILDING_ZYNTHBOX_DEPENDENCY: 1
        SKIP_ZYNTHBOX_DEPENDENCIES_INSTALLATION: 0

    steps:
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y build-essential devscripts debhelper lintian build-essential git swig subversion pkg-config autoconf automake premake4 gettext intltool libtool libtool-bin cmake cmake-curses-gui flex bison ngrep qt5-qmake gobjc++ ruby rake xsltproc vorbis-tools zenity ffmpeg libavformat-dev libavcodec-dev libfftw3-dev libmxml-dev zlib1g-dev fluid libfltk1.3-dev libfltk1.3-compat-headers libncurses5-dev liblo-dev dssi-dev libjpeg-dev libxpm-dev libcairo2-dev libglu1-mesa-dev libasound2-dev dbus-x11 jackd2 libjack-jackd2-dev a2jmidid libffi-dev fontconfig-config libfontconfig1-dev libxft-dev libexpat-dev libglib2.0-dev libgettextpo-dev libsqlite3-dev libglibmm-2.4-dev libeigen3-dev libsndfile-dev libsamplerate-dev libarmadillo-dev libreadline-dev lv2-c++-tools libxi-dev libgtk2.0-dev libgtkmm-2.4-dev liblrdf-dev libboost-system-dev libzita-convolver-dev libzita-resampler-dev fonts-roboto libxcursor-dev libxinerama-dev mesa-common-dev libgl1-mesa-dev libfreetype6-dev libswscale-dev qtbase5-dev qtdeclarative5-dev libcanberra-gtk-module libcanberra-gtk3-module libxcb-cursor-dev libgtk-3-dev libxcb-util0-dev libxcb-keysyms1-dev libxcb-xkb-dev libxkbcommon-x11-dev libssl-dev python3 python-is-python3 python3-dev cython3 python3-cffi python3-tk python3-dbus python3-mpmath python3-pil python3-pil.imagetk python3-setuptools python3-pyqt5 python3-numpy python3-evdev 2to3 python3-pip libfreetype-dev meson extra-cmake-modules tree

      - uses: actions/checkout@v2

      - name: Download tar from github release and create orig.tar.gz
        run: |
          PACKAGE_NAME=$(dpkg-parsechangelog --show-field Source)
          PACKAGE_VERSION=$(dpkg-parsechangelog --show-field Version | sed 's/-[^-]*$//')

          # Keep the debian folder backup
          mv debian debian.bkup

          wget -O ../${PACKAGE_NAME}_${PACKAGE_VERSION}.orig.tar.gz https://github.com/zynthbox/zynthbox-dependencies/releases/download/RC-5/synthv1-lv2-1.3.0.tar.gz
          tar -xf ../${PACKAGE_NAME}_${PACKAGE_VERSION}.orig.tar.gz -C ./ --strip-components=1

          rm -rf debian
          mv debian.bkup debian

          
      - name: Build DEB using Debhelper
        run: |
          set -x
          apt-get -y update
          apt-get -y --no-install-recommends install gnupg2 curl wget sudo openssh-client

          # Ensuring key security
          mkdir -p ~/.ssh
          echo "${{ secrets.APTLY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan repo.zynthbox.io >> ~/.ssh/known_hosts

          # Zynthbox repo
          curl -L https://repo.zynthbox.io/repo_key.pub | apt-key add -;
          if [ "$RELEASE" = "bookworm" ]; then
            echo "deb https://repo.zynthbox.io/testing-bookworm/ bookworm main" | tee "/etc/apt/sources.list.d/zynthbox.list"
            echo "deb https://repo.zynthbox.io/kxstudio/ bookworm main" | tee "/etc/apt/sources.list.d/zynthbox-kxstudio.list"
            echo "deb https://repo.zynthbox.io/deb-multimedia/ bookworm main" | tee "/etc/apt/sources.list.d/zynthbox-debmultimedia.list"
          else
            echo "UNKNOWN RELEASE $RELEASE"
          fi

          # lv2-dev package from kxstudio is missing header files. Give priority to deb-multimedia one when installing and make sure kxstudio one never gets installed
          echo "Package: lv2-dev" >> /etc/apt/preferences.d/lv2-dev
          echo "Pin: origin www.deb-multimedia.org" >> /etc/apt/preferences.d/lv2-dev
          echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/lv2-dev
          echo "" >> /etc/apt/preferences.d/lv2-dev
          echo "Package: lv2-dev" >> /etc/apt/preferences.d/lv2-dev
          echo "Pin: origin ppa.launchpad.net" >> /etc/apt/preferences.d/lv2-dev
          echo "Pin-Priority: 1" >> /etc/apt/preferences.d/lv2-dev
          echo "" >> /etc/apt/preferences.d/lv2-dev

          ### Make the aptly jobs wait on a global lock file so that the aptly jobs are mutually exclusive
          ### Create a lock file /tmp/publish-aptly-zynthbox.lock and cleanup before completing the job
          echo "Checking if /tmp/publish-aptly-zynthbox.lock exists"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'while [ -f /tmp/publish-aptly-zynthbox.lock ]; do echo "/tmp/publish-aptly-zynthbox.lock exists. Waiting for other publish jobs to finish first"; sleep 5; done'

          apt-get -y update
          # If BUILDING_ZYNTHBOX_DEPENDENCY is set to 1 then install a bunch of packages required for building the dependencies or plugins
          if [ "$BUILDING_ZYNTHBOX_DEPENDENCY" -eq 1 ]; then
            # Do not install zynthbox dependency packages if set to 1
            if [ "$SKIP_ZYNTHBOX_DEPENDENCIES_INSTALLATION" -eq 0 ]; then
              apt-get -y --no-install-recommends install build-essential git swig subversion pkg-config autoconf automake premake4 gettext intltool libtool libtool-bin cmake cmake-curses-gui flex bison ngrep qt5-qmake gobjc++ ruby rake xsltproc vorbis-tools zenity ffmpeg libavformat-dev libavcodec-dev libfftw3-dev libmxml-dev zlib1g-dev fluid libfltk1.3-dev libfltk1.3-compat-headers libncurses5-dev liblo-dev dssi-dev libjpeg-dev libxpm-dev libcairo2-dev libglu1-mesa-dev libasound2-dev dbus-x11 jackd2 libjack-jackd2-dev a2jmidid libffi-dev fontconfig-config libfontconfig1-dev libxft-dev libexpat-dev libglib2.0-dev libgettextpo-dev libsqlite3-dev libglibmm-2.4-dev libeigen3-dev libsndfile-dev libsamplerate-dev libarmadillo-dev libreadline-dev lv2-c++-tools libxi-dev libgtk2.0-dev libgtkmm-2.4-dev liblrdf-dev libboost-system-dev libzita-convolver-dev libzita-resampler-dev fonts-roboto libxcursor-dev libxinerama-dev mesa-common-dev libgl1-mesa-dev libfreetype6-dev libswscale-dev qtbase5-dev qtdeclarative5-dev libcanberra-gtk-module libcanberra-gtk3-module libxcb-cursor-dev libgtk-3-dev libxcb-util0-dev libxcb-keysyms1-dev libxcb-xkb-dev libxkbcommon-x11-dev libssl-dev python3 python-is-python3 python3-dev cython3 python3-cffi python3-tk python3-dbus python3-mpmath python3-pil python3-pil.imagetk python3-setuptools python3-pyqt5 python3-numpy python3-evdev 2to3 python3-pip libfreetype-dev meson extra-cmake-modules tree
            fi
          fi

          # Set C/CXX FLAGS to optimize builds for RPI4
          export CFLAGS="-ftree-vectorize -O2 -pipe -fomit-frame-pointer"
          export CXXFLAGS="${CFLAGS}"
          export CFLAGS_UNSAFE=""

          # Create world writable gnupg home
          export GNUPGHOME=$(mktemp -d /tmp/.gnupgXXXXXX)
          chmod 777 $GNUPGHOME

          # Create dpkg-buildpackage config to disable signing of source, build and changes files when generating debs
          echo "unsigned-source" >> /etc/dpkg/buildpackage.conf
          echo "unsigned-buildinfo" >> /etc/dpkg/buildpackage.conf
          echo "unsigned-changes" >> /etc/dpkg/buildpackage.conf
          set +x

          # Install the build dependencies reading the Build-Depends in the debian/control file
          apt-get -y build-dep .

          dpkg-buildpackage -us -uc
          pwd
          tree ../

      - name: Upload deb to aptly repo
        run: |
          set -x
          echo "Updating repository info"
          apt update

          mkdir -p ~/.ssh
          echo "${{ secrets.APTLY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan repo.zynthbox.io >> ~/.ssh/known_hosts

          ### Make the aptly jobs wait on a global lock file so that the aptly jobs are mutually exclusive
          ### Create a lock file /tmp/publish-aptly-zynthbox.lock and cleanup before completing the job
          echo "Checking if /tmp/publish-aptly-zynthbox.lock exists"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'while [ -f /tmp/publish-aptly-zynthbox.lock ]; do echo "/tmp/publish-aptly-zynthbox.lock exists. Waiting for other publish jobs to finish first"; sleep 5; done'
          echo "Creating lock file /tmp/publish-aptly-zynthbox.lock"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'touch /tmp/publish-aptly-zynthbox.lock'

          echo "Uploading debs"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ../*.deb aptly@repo.zynthbox.io:/mnt/pub_zynthbox_io_volume/temp/
          echo "Adding package(s) to repository"

          if [ "$RELEASE" = "bookworm" ]; then
            for pkg in $(ls -1 ../*.deb)
              do
                echo "Adding ${pkg}"
                ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'aptly repo add -remove-files '"${APTLY_REPO}-bookworm"' /mnt/pub_zynthbox_io_volume/temp/${pkg}'
            done
            echo "Publishing repository"
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'aptly publish update bookworm '"${APTLY_REPO}-bookworm"
            echo "Cleaning up"
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'if [[ -f /tmp/working ]];then rm /tmp/working;fi'
            echo "Generate list of packages"
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'aptly repo show -with-packages '"${APTLY_REPO}-bookworm"' > '"~/.aptly/public/${APTLY_REPO}-bookworm/${APTLY_REPO}-bookworm.list"
          else
            echo "CANNOT PUBLISH DEBS. UNKNOWN RELEASE $RELEASE"
          fi

          ### Delete lock file /tmp/publish-aptly-zynthbox.lock for other aptly jobs to continue
          echo "Removing lock file"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'if [[ -f /tmp/publish-aptly-zynthbox.lock ]]; then rm /tmp/publish-aptly-zynthbox.lock; fi'
          set +x
