name: Build zynthbox-plugin-synthv1-lv2 deb

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    container:
      image: debian:bookworm
      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y build-essential devscripts debhelper lintian tree

      - name: Build DEB using Debhelper
        run: |
          pwd
          tree
          dpkg-buildpackage -us -uc